# Theme Settings
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" # 

# Site Settings
locale                   : "en-US"
title                    : "SCID 2026"
title_separator          : "-"
subtitle                 : "First Spatial-Cell-ID Conference"
name                     : "SCID 2026"
description              : "First Spatial-Cell-ID - Workshop on Spatial Bioinformatics"

url                      : "https://spatial-cell-id.github.io" 
baseurl                  : "/scid2026" 

repository               : "spatial-cell-id/scid2026"
teaser                   : # path di un'immagine (es: /assets/images/teaser.jpg)
logo                     : # path del logo (es: /assets/images/logo.png)
masthead_title           : "SCID 2026"
breadcrumbs              : true # Aiuta la navigazione nelle sottopagine

# Site Author (Appare nella colonna sinistra)
author:
  name             : "SCID 2026"
  avatar           : # Metti un'immagine quadrata in /assets/images/logo.png e linkala qui
  bio              : "First Spatial-Cell-ID Summer School"
  location         : "Aussois, France"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:scid2026@sciencesconf.org" # Esempio


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme # Fondamentale per far funzionare il tema su GitHub

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true # Mostra la sidebar dell'autore in tutte le pagine
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false # Inutile per un sito di conferenza
      share: true
      related: true